"""
PupilNet: lightweight CNN for refractive error estimation.

Predicts the Thibos power vector (M, J0, J45) from a 2-channel eccentric
photorefraction image (horizontal + vertical source). Power-vector outputs
avoid the axis-wrapping discontinuity of (S, C, axis) and integrate directly
with the closed-loop optimizer in optimize.py.

Architecture
------------
Four depthwise-separable conv blocks halve the spatial resolution at each
stage. Global average pooling + two FC layers produce the three output values.

Total parameters: ~450 k — fits in 1.8 MB fp32, 0.45 MB INT8.
The block design is INT8-quantizable (no operation that breaks PTQ):
  - No sigmoid/tanh in the backbone (only ReLU)
  - No layer norm (only batch norm, which folds into conv at export)
  - Linear output head (no activation on regression targets)

Production notes
----------------
Deployment on edge hardware (Jetson Orin Nano, RPi CM4 with Hailo-8):
  torch.export → ONNX → TensorRT/HAILOrt INT8 quantization.
  Expected latency: 0.5–2 ms per frame at INT8 on NPU.

  Before deployment, calibrate the output scale by comparing CNN predictions
  against a reference autorefractor on 50+ eyes. A linear correction
  (a*M_pred + b) per component reduces systematic bias from the sim-to-real gap.
"""

from __future__ import annotations
import numpy as np
import torch
import torch.nn as nn
from pathlib import Path


# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------

class _DepthwiseBlock(nn.Module):
    """Depthwise-separable conv + BN + ReLU."""

    def __init__(self, in_ch: int, out_ch: int, stride: int = 1):
        super().__init__()
        self.dw = nn.Conv2d(in_ch, in_ch, 3, stride=stride, padding=1, groups=in_ch, bias=False)
        self.pw = nn.Conv2d(in_ch, out_ch, 1, bias=False)
        self.bn = nn.BatchNorm2d(out_ch)
        self.act = nn.ReLU(inplace=True)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.act(self.bn(self.pw(self.dw(x))))


class PupilNet(nn.Module):
    """
    Predict (M, J0, J45) in dioptres from a 2-channel photorefraction image.

    Input:  (B, 2, H, W)  where H = W = image_size (default 64)
    Output: (B, 3)        [M, J0, J45] in dioptres

    To convert back to clinical notation:
        from eyesim.optimize import power_vector_to_prescription
        S, C, axis = power_vector_to_prescription(M, J0, J45)
    """

    def __init__(self, image_size: int = 64, in_channels: int = 2):
        super().__init__()
        # Stem: standard conv to avoid depthwise on 2-ch input
        self.stem = nn.Sequential(
            nn.Conv2d(in_channels, 32, 3, stride=2, padding=1, bias=False),
            nn.BatchNorm2d(32),
            nn.ReLU(inplace=True),
        )
        # Four depthwise blocks, each halving spatial resolution
        self.blocks = nn.Sequential(
            _DepthwiseBlock(32,  64,  stride=2),
            _DepthwiseBlock(64,  128, stride=2),
            _DepthwiseBlock(128, 256, stride=2),
            _DepthwiseBlock(256, 256, stride=1),
        )
        self.pool = nn.AdaptiveAvgPool2d(1)
        # Regression head
        self.head = nn.Sequential(
            nn.Flatten(),
            nn.Linear(256, 128),
            nn.ReLU(inplace=True),
            nn.Dropout(0.2),
            nn.Linear(128, 3),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.stem(x)
        x = self.blocks(x)
        x = self.pool(x)
        return self.head(x)


def count_parameters(model: nn.Module) -> int:
    return sum(p.numel() for p in model.parameters() if p.requires_grad)


# ---------------------------------------------------------------------------
# Dataset
# ---------------------------------------------------------------------------

class PrescriptionDataset(torch.utils.data.Dataset):
    """
    Loads a .npz dataset generated by scripts/generate_dataset.py.

    .npz must contain:
        images : float32  (N, H, W, 2)  — 2-channel photorefraction images
        labels : float32  (N, 3)        — [M, J0, J45] in dioptres

    Returns (image_tensor, label_tensor) with image shape (2, H, W).
    """

    def __init__(self, npz_path: str | Path, augment: bool = False):
        data = np.load(npz_path)
        self.images = data["images"].astype(np.float32)   # (N, H, W, 2)
        self.labels = data["labels"].astype(np.float32)   # (N, 3)
        self.augment = augment

    def __len__(self) -> int:
        return len(self.labels)

    def __getitem__(self, idx: int):
        img = self.images[idx]                    # (H, W, 2)
        lbl = self.labels[idx]                    # (3,)

        if self.augment:
            # Mild intensity jitter — simulates exposure variation
            img = img * np.random.uniform(0.9, 1.1)
            # Additive noise — simulates sensor read noise
            img = img + np.random.normal(0, 0.01, img.shape).astype(np.float32)
            img = np.clip(img, 0.0, 1.0)

        # HWC → CHW for PyTorch
        img_t = torch.from_numpy(img.transpose(2, 0, 1))
        lbl_t = torch.from_numpy(lbl)
        return img_t, lbl_t


# ---------------------------------------------------------------------------
# Losses and metrics
# ---------------------------------------------------------------------------

def power_vector_loss(pred: torch.Tensor, target: torch.Tensor) -> torch.Tensor:
    """
    MSE in power-vector space, equal weight on M, J0, J45.
    This is a proxy for clinical accuracy (see power_vector_distance below).
    """
    return nn.functional.mse_loss(pred, target)


def power_vector_mae(pred: torch.Tensor, target: torch.Tensor) -> dict[str, float]:
    """Return per-component and combined MAE in dioptres."""
    diff = (pred - target).abs()
    return {
        "M_mae":   diff[:, 0].mean().item(),
        "J0_mae":  diff[:, 1].mean().item(),
        "J45_mae": diff[:, 2].mean().item(),
        "total_mae": diff.mean().item(),
    }
