"""
Train PupilNet to predict refractive error from photorefraction images.

Requires dataset generated by scripts/generate_dataset.py.
Saves the best checkpoint (lowest val loss) to checkpoints/best.pt.

Training recipe
---------------
  Optimizer : AdamW  lr=1e-3  weight_decay=1e-4
  Schedule  : CosineAnnealingLR (T_max = n_epochs)
  Loss      : MSE on (M, J0, J45) power vector
  Epochs    : 100 (typically converges by 60)
  Batch     : 256 on GPU / 64 on CPU

Target metrics (100 k augmented samples, 100 epochs, single A100)
------------------------------------------------------------------
  Val M   MAE < 0.15 D
  Val J0  MAE < 0.08 D
  Val J45 MAE < 0.08 D

Usage
-----
  python scripts/train.py --data data --epochs 100 --batch 256
  python scripts/train.py --data data --epochs 10  --batch 64   # quick smoke test
"""

import argparse
import time
from pathlib import Path

import torch
import torch.nn as nn
from torch.utils.data import DataLoader

import sys
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from eyesim.cnn import PupilNet, PrescriptionDataset, power_vector_loss, power_vector_mae, count_parameters


def train_one_epoch(model, loader, optimizer, device):
    model.train()
    total_loss = 0.0
    for imgs, lbls in loader:
        imgs, lbls = imgs.to(device), lbls.to(device)
        optimizer.zero_grad()
        pred = model(imgs)
        loss = power_vector_loss(pred, lbls)
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * imgs.size(0)
    return total_loss / len(loader.dataset)


@torch.no_grad()
def evaluate(model, loader, device):
    model.eval()
    total_loss = 0.0
    all_pred, all_target = [], []
    for imgs, lbls in loader:
        imgs, lbls = imgs.to(device), lbls.to(device)
        pred = model(imgs)
        total_loss += power_vector_loss(pred, lbls).item() * imgs.size(0)
        all_pred.append(pred.cpu())
        all_target.append(lbls.cpu())
    pred_cat   = torch.cat(all_pred)
    target_cat = torch.cat(all_target)
    mae = power_vector_mae(pred_cat, target_cat)
    return total_loss / len(loader.dataset), mae


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data",     default="data",          help="directory with train/val.npz")
    ap.add_argument("--epochs",   type=int,   default=100)
    ap.add_argument("--batch",    type=int,   default=256)
    ap.add_argument("--lr",       type=float, default=1e-3)
    ap.add_argument("--wd",       type=float, default=1e-4, help="weight decay")
    ap.add_argument("--workers",  type=int,   default=4)
    ap.add_argument("--out",      default="checkpoints",   help="checkpoint directory")
    ap.add_argument("--size",     type=int,   default=64,  help="image size")
    args = ap.parse_args()

    device = (
        torch.device("cuda")  if torch.cuda.is_available()  else
        torch.device("mps")   if torch.backends.mps.is_available() else
        torch.device("cpu")
    )
    print(f"Device: {device}")

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    data_dir = Path(args.data)
    train_ds = PrescriptionDataset(data_dir / "train.npz", augment=True)
    val_ds   = PrescriptionDataset(data_dir / "val.npz",   augment=False)

    train_loader = DataLoader(train_ds, batch_size=args.batch, shuffle=True,
                              num_workers=args.workers, pin_memory=True)
    val_loader   = DataLoader(val_ds,   batch_size=args.batch * 2, shuffle=False,
                              num_workers=args.workers, pin_memory=True)

    model = PupilNet(image_size=args.size).to(device)
    print(f"PupilNet  {count_parameters(model):,} parameters")

    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=args.wd)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=args.epochs)

    best_val_loss = float("inf")
    log_path = out_dir / "train_log.csv"
    with open(log_path, "w") as f:
        f.write("epoch,train_loss,val_loss,M_mae,J0_mae,J45_mae,lr,elapsed_s\n")

    t0 = time.time()
    for epoch in range(1, args.epochs + 1):
        train_loss = train_one_epoch(model, train_loader, optimizer, device)
        val_loss, mae = evaluate(model, val_loader, device)
        scheduler.step()
        elapsed = time.time() - t0
        lr_now = scheduler.get_last_lr()[0]

        print(
            f"Epoch {epoch:3d}/{args.epochs}  "
            f"train={train_loss:.4f}  val={val_loss:.4f}  "
            f"M={mae['M_mae']:.3f}  J0={mae['J0_mae']:.3f}  J45={mae['J45_mae']:.3f}  "
            f"lr={lr_now:.2e}  {elapsed:.0f}s"
        )

        with open(log_path, "a") as f:
            f.write(f"{epoch},{train_loss:.6f},{val_loss:.6f},"
                    f"{mae['M_mae']:.6f},{mae['J0_mae']:.6f},{mae['J45_mae']:.6f},"
                    f"{lr_now:.6e},{elapsed:.1f}\n")

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save({
                "epoch": epoch,
                "model_state_dict": model.state_dict(),
                "optimizer_state_dict": optimizer.state_dict(),
                "val_loss": val_loss,
                "mae": mae,
            }, out_dir / "best.pt")
            print(f"  -> saved best checkpoint (val_loss={val_loss:.6f})")

    print(f"\nTraining complete. Best val_loss = {best_val_loss:.6f}")
    print(f"Checkpoint: {out_dir / 'best.pt'}")
    print(f"Log: {log_path}")


if __name__ == "__main__":
    main()
